import CardTestimony from '@/components/CardTestimony'
import ContactForm from '@/components/ContactForm'
import Footer from '@/components/Footer'
import HeroPageSection from '@/components/HeroPageSection'
import Navbar from '@/components/Navbar'
import OurServicesSection from '@/components/OurServicesSection'
import Head from 'next/head'
import React from 'react'
import StyleSheet from '../../styles'

function OurServices() {
  return (
    <>
      <Head>
        <title>Our Services | Schadtle Outdoor Services</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <>
        <Navbar />
        <main className='pt-[100px] mb-32'>
          <HeroPageSection
            title={'What Services we offer our Clients'}
            content={`We works closely with clients to understand their unique needs and goals, and provides high-quality, personalised services that enhance the beauty and functionality of their outdoor spaces.`}
          />
        </main>
        <section className='px-8 mb-32 md:px-12 lg:px-32'>
          <div className='mb-8 lg:mb-32'>
            <OurServicesSection
              img={'../images/services_img/services_one.png'}
              title={'Retaining Walls design & Construction'}
              content={`We’d love to hear from you! Give us call, send us a message or find us
              on the social media.`}
              learn={'Learn More'}
              link={'/our-services/retaining-walls'}
            />
          </div>
          <div className='mb-8 lg:mb-32'>
            <OurServicesSection
              img={'../images/services_img/services_two.png'}
              title={'Patios Design & Construction'}
              content={`We’d love to hear from you! Give us call, send us a message or find us
              on the social media.`}
              learn={'Learn More'}
              link={'/our-services/patios-design'}
              reverse={true}
            />
          </div>
          <div className='mb-8 lg:mb-32'>
            <OurServicesSection
              img={'../images/services_img/services_three.png'}
              title={'Steps Building'}
              content={`We’d love to hear from you! Give us call, send us a message or find us
              on the social media.`}
              learn={'Learn More'}
              link={'/our-services/steps-building'}
            />
          </div>
          <div className='mb-8 lg:mb-32'>
            <OurServicesSection
              img={'../images/services_img/services_four.png'}
              title={'Stump Grinding'}
              content={`We’d love to hear from you! Give us call, send us a message or find us
              on the social media.`}
              learn={'Learn More'}
              link={'/our-services/stump-grinding'}
              reverse={true}
            />
          </div>
          <div className='mb-8 lg:mb-32'>
            <OurServicesSection
              img={'../images/services_img/services_five.png'}
              title={'Walkway Design and Construction'}
              content={`We’d love to hear from you! Give us call, send us a message or find us
              on the social media.`}
              learn={'Learn More'}
              link={'/our-services/walkaway-design'}
            />
          </div>
          <div className=''>
            <OurServicesSection
              img={'../images/services_img/services_six.png'}
              title={'Yard Expansion Design & Construction'}
              content={`We’d love to hear from you! Give us call, send us a message or find us
              on the social media.`}
              learn={'Learn More'}
              link={'/our-services/yard-expansion'}
              reverse={true}
            />
          </div>
        </section>
        <section className='px-8 mb-32 md:px-12 lg:px-32'>
          <div className='flex flex-col gap-2 mb-12'>
            <h2 className={StyleSheet.HeadingContent.heading}>Testimony</h2>
            <p className={StyleSheet.HeadingContent.content}>
              Our clients are all praise for us about our exploits
            </p>
          </div>
          <div className='grid grid-cols-1 gap-8 md:grid-cols-2 lg:grid-cols-3'>
            <CardTestimony
              desc={`Vertical pixel horizontal main group rectangle strikethrough stroke
            bold. Star community underline star font share content plugin layout
            slice. Library export font star editor library. Ellipse.`}
              img={'../images/testimonial.png'}
              name={'Tunde Ajayi'}
              location={'Location'}
              starIcon={'../star.svg'}
              alt={'tunde_ajayi'}
              source={'Trust Pilot'}
            />
            <CardTestimony
              desc={`Vertical pixel horizontal main group rectangle strikethrough stroke
            bold. Star community underline star font share content plugin layout
            slice. Library export font star editor library. Ellipse.`}
              img={'../images/testimonial.png'}
              name={'Tunde Ajayi'}
              location={'Location'}
              starIcon={'../star.svg'}
              alt={'tunde_ajayi'}
              source={'Trust Pilot'}
            />
            <CardTestimony
              desc={`Vertical pixel horizontal main group rectangle strikethrough stroke
            bold. Star community underline star font share content plugin layout
            slice. Library export font star editor library. Ellipse.`}
              img={'../images/testimonial.png'}
              name={'Tunde Ajayi'}
              location={'Location'}
              starIcon={'../star.svg'}
              alt={'tunde_ajayi'}
              source={'Trust Pilot'}
            />
          </div>
        </section>
        <section className='px-8 mb-32 md:px-12 lg:px-32'>
          <ContactForm />
        </section>
        <footer className="bg-[url('/images/footer_background.png')] bg-cover bg-center">
          <Footer />
        </footer>
      </>
    </>
  )
}

export default OurServices
