import ContactForm from '@/components/ContactForm'
import Footer from '@/components/Footer'
import Navbar from '@/components/Navbar'
import Head from 'next/head'
import { useRouter } from 'next/router'
import React from 'react'

function BlogSlug() {
  const router = useRouter()
  return (
    <>
      <Head>
        <title>Our Services | Schadtle Outdoor Services</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <>
        <Navbar />
        <section className='pt-[172px] px-8 mb-8 md:px-12 lg:px-32 lg:mb-16'></section>
        <div className='flex flex-col gap-6 mb-[52px]  px-8 md:px-12 lg:pl-[179px] lg:pr-[279px] lg:gap-8'>
          <h2 className='font-sora font-normal text-[30px] text-[#315C1E] leading-tight md:text-[35px] lg:leading-[64px] lg:text-[56px]'>
            5 Benefits of Adding a Custom Outdoor Fireplace to Your Backyard
          </h2>
          <p className='font-sora font-light text-base text-[#807B84] leading-24'>
            By John Doe | Feb 14, 2023
          </p>
        </div>
        <div className='px-8 md:px-12 lg:px-32 mb-[52px]'>
          <img src='../../images/singleblog.png' alt='Single Blog Image' />
        </div>
        <article className='flex flex-col mb-[193px] gap-4 px-8 md:px-12 lg:pl-[229.5px]  lg:pr-[228.5px]'>
          <p className='font-sora font-light text-base text-greyish-primary leading-[30px] lg:leading-40 lg:text-[20px]'>
            Outdoor fireplaces have been increasing in popularity in recent
            years, and it&apos;s not difficult to see why. They provide a cozy
            and inviting space for outdoor gatherings, and can be customized to
            fit any style or preference. In this blog post, we&apos;ll explore
            the top five benefits of adding a custom outdoor fireplace to your
            backyard.
          </p>
          <ol className='list-decimal pl-5 flex flex-col gap-4 font-sora font-light leading-[30px] text-base text-greyish-primary lg:pl-8 lg:leading-40 lg:text-[20px]'>
            <li>
              Creates a warm and inviting atmosphere An outdoor fireplace
              creates a warm and inviting atmosphere in your backyard. Whether
              you&apos;re hosting a party, or just relaxing with your family, an
              outdoor fireplace will provide a cozy ambiance and make your
              outdoor living space feel like an extension of your home.
            </li>
            <li>
              Increases the value of your home Adding a custom outdoor fireplace
              to your backyard can increase the value of your home. It&apos;s a
              unique feature that many homebuyers look for, and it can make your
              home stand out from the rest. Plus, a custom fireplace can be
              designed to fit the style of your home and enhance its overall
              aesthetic.
            </li>
            <li>
              Provides a source of light and warmth An outdoor fireplace not
              only provides warmth, but it also provides a source of light. This
              is perfect for those summer nights when you want to spend time
              outside, but it gets too dark to see. You can enjoy the warmth of
              the fire, and the soft glow of the flames.
            </li>
            <li>
              Ideal for outdoor cooking An outdoor fireplace is ideal for
              outdoor cooking. You can cook everything from pizzas to steaks and
              everything in between. The heat from the fire can be used to cook
              food, and the smoky flavor adds a delicious taste to your meals.
              This is perfect for those summer barbecues and parties.
            </li>
            <li>
              Low maintenance An outdoor fireplace is a low maintenance addition
              to your backyard. It&apos;s built to last, and requires little
              maintenance. All you need to do is clean it regularly and make
              sure it&apos;s in good condition. This makes it a cost-effective
              addition to your home that will provide years of enjoyment.
            </li>
          </ol>
          <p className='font-sora font-light text-base leading-[30px] text-greyish-primary lg:leading-40 lg:text-[20px]'>
            In conclusion, adding a custom outdoor fireplace to your backyard
            provides a warm and inviting atmosphere, increases the value of your
            home, provides a source of light and warmth, is ideal for outdoor
            cooking, and is a low-maintenance addition to your home. It&apos;s
            no wonder why more and more homeowners are opting for this unique
            and practical addition to their outdoor living space.
          </p>
        </article>
        <section className='px-8 mb-32 md:px-12 lg:px-32'>
          <ContactForm />
        </section>
        <footer className="bg-[url('/images/footer_background.png')] bg-cover bg-center">
          <Footer />
        </footer>
      </>
    </>
  )
}

export default BlogSlug
