import BlogPost from '@/components/BlogPost'
import Footer from '@/components/Footer'
import HeroPageSection from '@/components/HeroPageSection'
import Navbar from '@/components/Navbar'
import Head from 'next/head'
import React from 'react'

function Blog() {
  return (
    <>
      <Head>
        <title>Our Services | Schadtle Outdoor Services</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <>
        <Navbar />
        <main className='pt-[100px] mb-32'>
          <HeroPageSection
            title={`News, Tips & Tricks from Our Blog`}
            content={`At Schadtle’s Outdoor Services, we don't just get the job done, we're committed to sharing our knowledge for a better planet.`}
          />
        </main>
        <article className='mb-32 px-8 md:px-12 lg:px-32'>
          <div className='grid grid-cols-1 gap-8 mb-12 lg:grid-cols-3'>
            <BlogPost
              title={`5 Benefits of Adding a Custom Outdoor Fireplace to Your Backyard`}
              date={`02 Jan, 2023`}
              author={`Author Name`}
              content={` Pencil layout ipsum reesizing stroke blur union inspect follower font.
              Device connection ipsum connection auto. Follower connection selection
              content content. Follower.`}
              readMore={`Read More`}
              link={'/blog/blog-slug'}
            />
            <BlogPost
              title={`5 Benefits of Adding a Custom Outdoor Fireplace to Your Backyard`}
              date={`02 Jan, 2023`}
              author={`Author Name`}
              content={` Pencil layout ipsum reesizing stroke blur union inspect follower font.
              Device connection ipsum connection auto. Follower connection selection
              content content. Follower.`}
              readMore={`Read More`}
              link={'/blog/blog-slug'}
            />
            <BlogPost
              title={`5 Benefits of Adding a Custom Outdoor Fireplace to Your Backyard`}
              date={`02 Jan, 2023`}
              author={`Author Name`}
              content={` Pencil layout ipsum reesizing stroke blur union inspect follower font.
              Device connection ipsum connection auto. Follower connection selection
              content content. Follower.`}
              readMore={`Read More`}
              link={'/blog/blog-slug'}
            />
          </div>
          <div className='grid grid-cols-1 gap-8 mb-12 lg:grid-cols-3'>
            <BlogPost
              title={`5 Benefits of Adding a Custom Outdoor Fireplace to Your Backyard`}
              date={`02 Jan, 2023`}
              author={`Author Name`}
              content={` Pencil layout ipsum reesizing stroke blur union inspect follower font.
              Device connection ipsum connection auto. Follower connection selection
              content content. Follower.`}
              readMore={`Read More`}
              link={'/blog/blog-slug'}
            />
            <BlogPost
              title={`5 Benefits of Adding a Custom Outdoor Fireplace to Your Backyard`}
              date={`02 Jan, 2023`}
              author={`Author Name`}
              content={` Pencil layout ipsum reesizing stroke blur union inspect follower font.
              Device connection ipsum connection auto. Follower connection selection
              content content. Follower.`}
              readMore={`Read More`}
              link={'/blog/blog-slug'}
            />
            <BlogPost
              title={`5 Benefits of Adding a Custom Outdoor Fireplace to Your Backyard`}
              date={`02 Jan, 2023`}
              author={`Author Name`}
              content={` Pencil layout ipsum reesizing stroke blur union inspect follower font.
              Device connection ipsum connection auto. Follower connection selection
              content content. Follower.`}
              readMore={`Read More`}
              link={'/blog/blog-slug'}
            />
          </div>
          <div className='grid grid-cols-1 gap-8 mb-12 lg:grid-cols-3'>
            <BlogPost
              title={`5 Benefits of Adding a Custom Outdoor Fireplace to Your Backyard`}
              date={`02 Jan, 2023`}
              author={`Author Name`}
              content={` Pencil layout ipsum reesizing stroke blur union inspect follower font.
              Device connection ipsum connection auto. Follower connection selection
              content content. Follower.`}
              readMore={`Read More`}
              link={'/blog/blog-slug'}
            />
            <BlogPost
              title={`5 Benefits of Adding a Custom Outdoor Fireplace to Your Backyard`}
              date={`02 Jan, 2023`}
              author={`Author Name`}
              content={` Pencil layout ipsum reesizing stroke blur union inspect follower font.
              Device connection ipsum connection auto. Follower connection selection
              content content. Follower.`}
              readMore={`Read More`}
              link={'/blog/blog-slug'}
            />
            <BlogPost
              title={`5 Benefits of Adding a Custom Outdoor Fireplace to Your Backyard`}
              date={`02 Jan, 2023`}
              author={`Author Name`}
              content={` Pencil layout ipsum reesizing stroke blur union inspect follower font.
              Device connection ipsum connection auto. Follower connection selection
              content content. Follower.`}
              readMore={`Read More`}
              link={'/blog/blog-slug'}
            />
          </div>
          <div className='grid grid-cols-1 gap-8 mb-12 lg:grid-cols-3'>
            <BlogPost
              title={`5 Benefits of Adding a Custom Outdoor Fireplace to Your Backyard`}
              date={`02 Jan, 2023`}
              author={`Author Name`}
              content={` Pencil layout ipsum reesizing stroke blur union inspect follower font.
              Device connection ipsum connection auto. Follower connection selection
              content content. Follower.`}
              readMore={`Read More`}
              link={'/blog/blog-slug'}
            />
            <BlogPost
              title={`5 Benefits of Adding a Custom Outdoor Fireplace to Your Backyard`}
              date={`02 Jan, 2023`}
              author={`Author Name`}
              content={` Pencil layout ipsum reesizing stroke blur union inspect follower font.
              Device connection ipsum connection auto. Follower connection selection
              content content. Follower.`}
              readMore={`Read More`}
              link={'/blog/blog-slug'}
            />
            <BlogPost
              title={`5 Benefits of Adding a Custom Outdoor Fireplace to Your Backyard`}
              date={`02 Jan, 2023`}
              author={`Author Name`}
              content={` Pencil layout ipsum reesizing stroke blur union inspect follower font.
              Device connection ipsum connection auto. Follower connection selection
              content content. Follower.`}
              readMore={`Read More`}
              link={'/blog/blog-slug'}
            />
          </div>
          <div className='flex flex-col items-center'>
            <button className='px-8 py-4 border rounded-lg border-menu-bg text-base font-semibold leading-24 text-menu-bg'>
              View More
            </button>
          </div>
        </article>
        <footer className="bg-[url('/images/footer_background.png')] bg-cover bg-center">
          <Footer />
        </footer>
      </>
    </>
  )
}

export default Blog
