import CardTestimony from '@/components/CardTestimony'
import ContactForm from '@/components/ContactForm'
import Footer from '@/components/Footer'
import HeroPageSection from '@/components/HeroPageSection'
import Navbar from '@/components/Navbar'
import OurStory from '@/components/OurStory'
import Team from '@/components/Team'
import Head from 'next/head'
import React from 'react'
import StyleSheet from '../styles'

function AboutUs() {
  return (
    <>
      <Head>
        <title>About Us | Schadtle Outdoor Services</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <>
        <Navbar />
        <main className='pt-[100px] mb-32'>
          <HeroPageSection
            title={'About Schadtle Outdoor Services'}
            content={`Get to know Schadtle, the full-service landscaping company based in
          Marlborough, that is committed to creating beautiful outdoor spaces
          while also caring for the planet.`}
          />
        </main>
        <section className='px-8 mb-24 md:px-12 lg:px-32'>
          <h2 className={`${StyleSheet.HeadingContent.heading} mb-8`}>
            Our Story
          </h2>
          <OurStory
            paraOne={`Schadtle’s Outdoor Services, the full-service landscaping company
          based in Marlborough, was founded with a simple goal in mind: to
          create beautiful outdoor spaces that people can enjoy and take pride
          in.`}
            paraTwo={`The company's founder, Joe Schadtle, had always been passionate
          about landscaping, and he knew that he wanted to turn that passion
          into a successful business. At the heart of Schadtle's outdoor
          services is a commitment to sustainability and environmental
          stewardship.`}
            paraThree={`The team at Schadtle believes that beautiful landscapes don't
          have to come at the cost of the planet, and they work tirelessly to
          create outdoor spaces that are not only aesthetically pleasing, but
          also eco-friendly.`}
            paraFour={`The team at Schadtle takes great pride in their work, and they are
            dedicated to providing exceptional customer service. From the initial
            consultation to the final installation, they work closely with their
            clients to ensure that their outdoor spaces meet their vision and
            exceed their expectations.`}
            paraFive={`Over the years, Schadtle has built a reputation as one of the most
            trusted and reliable landscaping companies in the Marlborough area.
            They have worked with countless homeowners, business owners, and
            community organizations, helping to create outdoor spaces that are not
            only beautiful, but also sustainable and environmentally friendly.`}
            paraSix={`In the end, Schadtle's outdoor services are about much more than
            just creating beautiful landscapes. They are about creating spaces
            where people can come together, relax, and enjoy the beauty of the
            natural world. And for the team at Schadtle, there's no greater
            satisfaction than knowing that they've helped make that possible
            for their clients.`}
          />
        </section>
        <section className='px-8 mb-32 md:px-12 lg:px-32'>
          <img
            className='object-cover'
            src='../images/story_image.png'
            alt='Story Image Section'
          />
        </section>
        <section className='px-8 mb-32 md:px-12 lg:px-32'>
          <div className='flex flex-col gap-4 mb-12'>
            <h3 className={StyleSheet.HeadingContent.heading}>Meet the Team</h3>
            <p className={StyleSheet.HeadingContent.content}>
              As team we got projects done faster and efficiently
            </p>
          </div>
          <div className='grid grid-cols-1 gap-8 md:grid-cols-2 lg:grid-cols-4'>
            <Team
              img={'../images/teams/Portrait Image.png'}
              name={'John Doe'}
              position={'Founder'}
            />
            <Team
              img={'../images/teams/Portrait Image-1.png'}
              name={'John Doe'}
              position={'Founder'}
            />
            <Team
              img={'../images/teams/Portrait Image-2.png'}
              name={'John Doe'}
              position={'Founder'}
            />
            <Team
              img={'../images/teams/Portrait Image-3.png'}
              name={'John Doe'}
              position={'Founder'}
            />
          </div>
        </section>
        <section className='px-8 mb-32 md:px-12 lg:px-32'>
          <h3 className={`${StyleSheet.HeadingContent.heading} mb-8`}>
            Discover our Approach
          </h3>
          <OurStory
            paraOne={`At Schadtle, we take a holistic approach to landscaping. We believe that creating beautiful outdoor spaces is about more than just planting flowers or laying down turf. Our team of experts takes into account the entire environment, from the soil composition to the available sunlight, to create a landscape that is not only beautiful, but also sustainable and functional.`}
            paraTwo={`One of our main priorities is to design and build outdoor spaces that are eco-friendly and beneficial to the environment. This means using locally sourced materials whenever possible, and implementing practices that conserve water and reduce waste. We also make a point to select plants that are well-suited to the local climate and require minimal maintenance.`}
            paraThree={`Another key aspect of our approach is our commitment to exceptional customer service. We work closely with our clients to understand their needs and desires, and to develop a custom plan that will transform their outdoor space into a place of beauty and relaxation. We pride ourselves on our open communication and transparency throughout the process, so that our clients are always in the loop and feel confident in the work we are doing.
            `}
            paraFour={`Finally, we believe that outdoor spaces should be enjoyed to their fullest extent, and we design our landscapes with this in mind. We create spaces that are not only visually stunning, but also functional and practical for outdoor activities, whether that means adding a custom outdoor fireplace, a patio for dining and entertaining, or a retaining wall to create more usable space. With our approach to landscaping, we strive to create outdoor spaces that are both beautiful and sustainable, and that bring joy to our clients for years to come.`}
          />
        </section>
        <section className='px-8 mb-32 md:px-12 lg:px-32'>
          <div className='flex flex-col gap-2 mb-12'>
            <h2 className={StyleSheet.HeadingContent.heading}>
              Client Reviews
            </h2>
            <p className={StyleSheet.HeadingContent.content}>
              Our Clients are satisfied the had all praise for us
            </p>
          </div>
          <div className='grid grid-cols-1 gap-8 md:grid-cols-2 lg:grid-cols-3'>
            <CardTestimony
              desc={`Vertical pixel horizontal main group rectangle strikethrough stroke
            bold. Star community underline star font share content plugin layout
            slice. Library export font star editor library. Ellipse.`}
              img={'../images/testimonial.png'}
              name={'Tunde Ajayi'}
              location={'Location'}
              starIcon={'../star.svg'}
              alt={'tunde_ajayi'}
              source={'Trust Pilot'}
            />
            <CardTestimony
              desc={`Vertical pixel horizontal main group rectangle strikethrough stroke
            bold. Star community underline star font share content plugin layout
            slice. Library export font star editor library. Ellipse.`}
              img={'../images/testimonial.png'}
              name={'Tunde Ajayi'}
              location={'Location'}
              starIcon={'../star.svg'}
              alt={'tunde_ajayi'}
              source={'Trust Pilot'}
            />
            <CardTestimony
              desc={`Vertical pixel horizontal main group rectangle strikethrough stroke
            bold. Star community underline star font share content plugin layout
            slice. Library export font star editor library. Ellipse.`}
              img={'../images/testimonial.png'}
              name={'Tunde Ajayi'}
              location={'Location'}
              starIcon={'../star.svg'}
              alt={'tunde_ajayi'}
              source={'Trust Pilot'}
            />
          </div>
        </section>
        <section className='px-8 mb-32 md:px-12 lg:px-32'>
          <ContactForm />
        </section>
        <footer className="bg-[url('/images/footer_background.png')] bg-cover bg-center">
          <Footer />
        </footer>
      </>
    </>
  )
}

export default AboutUs
