import CardTestimony from '@/components/CardTestimony'
import Footer from '@/components/Footer'
import HeroPageSection from '@/components/HeroPageSection'
import Navbar from '@/components/Navbar'
import WorkingHour from '@/components/WorkingHour'
import Head from 'next/head'
import React from 'react'

function ContactUs() {
  return (
    <>
      <Head>
        <title>Contact Us | Schadtle Outdoor Services</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <>
        <Navbar />
        <main className='pt-[100px] mb-32'>
          <HeroPageSection
            title={`Contact Schadtle
            Outdoor Services`}
            content={`We’d love to hear from you! Give us call, send us a message or find us on the social media.`}
          />
        </main>
        <section className='px-8 mb-32 md:px-12 lg:px-32'>
          <WorkingHour />
        </section>
        <section className='px-8 mb-32 md:px-12 lg:px-32'>
          <div className="relative bg-[url('/images/map.png')] h-[512px] rounded-2xl">
            <div className='absolute top-8 left-8 flex flex-col gap-2 bg-menu-bg w-[307px] rounded-2xl py-6 px-[26px]'>
              <h3 className='font-sora font-semibold text-base leading-32 text-white lg:text-[24px]'>
                Schadtle’s Office
              </h3>
              <p className='font-sora font-light text-sm leading-24 text-white lg:text-base'>
                252, West Road, Marlborough, CT 06447
              </p>
            </div>
          </div>
        </section>
        <section className='px-8 mb-32 md:px-12 lg:px-32'>
          <div className='flex flex-col gap-2 mb-12'>
            <h2 className='font-sora font-normal text-[30px] text-black leading-56 md:text-[35px] lg:text-[48px]'>
              Testimony
            </h2>
            <p className='font-sora font-normal text-base text-black leading-32 md:text-[20px] lg:text-[24px]'>
              Our clients are all praise for us about our exploits
            </p>
          </div>
          <div className='grid grid-cols-1 gap-8 md:grid-cols-2 lg:grid-cols-3'>
            <CardTestimony
              desc={`Vertical pixel horizontal main group rectangle strikethrough stroke
            bold. Star community underline star font share content plugin layout
            slice. Library export font star editor library. Ellipse.`}
              img={'../images/testimonial.png'}
              name={'Tunde Ajayi'}
              location={'Location'}
              starIcon={'../star.svg'}
              alt={'tunde_ajayi'}
              source={'Trust Pilot'}
            />
            <CardTestimony
              desc={`Vertical pixel horizontal main group rectangle strikethrough stroke
            bold. Star community underline star font share content plugin layout
            slice. Library export font star editor library. Ellipse.`}
              img={'../images/testimonial.png'}
              name={'Tunde Ajayi'}
              location={'Location'}
              starIcon={'../star.svg'}
              alt={'tunde_ajayi'}
              source={'Trust Pilot'}
            />
            <CardTestimony
              desc={`Vertical pixel horizontal main group rectangle strikethrough stroke
            bold. Star community underline star font share content plugin layout
            slice. Library export font star editor library. Ellipse.`}
              img={'../images/testimonial.png'}
              name={'Tunde Ajayi'}
              location={'Location'}
              starIcon={'../star.svg'}
              alt={'tunde_ajayi'}
              source={'Trust Pilot'}
            />
          </div>
        </section>
        <footer className="bg-[url('/images/footer_background.png')] bg-cover bg-center">
          <Footer />
        </footer>
      </>
    </>
  )
}

export default ContactUs
