import ContactForm from '@/components/ContactForm'
import Footer from '@/components/Footer'
import Navbar from '@/components/Navbar'
import ProjectDetails from '@/components/ProjectDetails'
import ProjectImgSection from '@/components/ProjectImgSection'
import Head from 'next/head'
import React from 'react'

function ProjectView() {
  return (
    <>
      <Head>
        <title>Project View | Schadtle Outdoor Services</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <>
        <Navbar />
        <section className='pt-[172px] px-8 mb-16 md:px-12 lg:px-32'></section>
        <section className='px-8 md:px-12 lg:px-32'>
          <ProjectDetails
            title={'Retaining Wall Project'}
            location={' Marlborough, Connecticut'}
            content={`We built a custom retaining wall for a client in Marlborough with a
            sloped backyard to prevent erosion and create a level outdoor living
            space. The wall was built using high-quality materials, reinforced
            with gravel layers, and drainage solutions were installed to prevent
            water buildup. The final result was a stunning and functional
            retaining wall that exceeded the client's expectations.`}
            contentType={'Private Residential Project '}
            duration={'Duration'}
            img={'../images/projectdetail.png'}
          />
        </section>
        <section className='grid grid-cols-1 gap-8 mb-8 px-8 md:px-12 lg:px-32 lg:grid-cols-2'>
          <ProjectImgSection
            img={'../images/projects_details/yarn_one.png'}
            title={'Before'}
          />
          <ProjectImgSection
            img={'../images/projects_details/yarn_two.png'}
            title={'After'}
          />
        </section>
        <section className='mb-8 px-8 md:px-12 lg:px-32'>
          <div>
            <img
              src='../images/projects_details/large_img.png'
              alt='Project details'
            />
          </div>
        </section>
        <section className='px-8 mb-32 md:px-12 lg:px-32'>
          <div className='grid grid-cols-1 mb-8 md:grid-cols-3 gap-8'>
            <img src='../images/projects_details/card_img_one.png' alt='' />
            <img src='../images/projects_details/card_img_two.png' alt='' />
            <img src='../images/projects_details/card_img_three.png' alt='' />
          </div>
          <div>
            <button className='px-8 py-4 bg-[#B5DC58] rounded-lg font-sora font-semibold text-base leading-24 text-[#3E3C40]'>
              View All
            </button>
          </div>
        </section>
        <section className='px-8 mb-32 md:px-12 lg:px-32'>
          <ContactForm />
        </section>
        <footer className="bg-[url('/images/footer_background.png')] bg-cover bg-center">
          <Footer />
        </footer>
      </>
    </>
  )
}

export default ProjectView
