import ContactForm from '@/components/ContactForm'
import Footer from '@/components/Footer'
import Navbar from '@/components/Navbar'
import SingleBlogContent from '@/components/SingleBlogContent'
import Head from 'next/head'
import React from 'react'

function SingleBlog() {
  return (
    <>
      <Head>
        <title>Our Services | Schadtle Outdoor Services</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <>
        <Navbar />
        <section className='pt-[172px] px-8 mb-8 md:px-12 lg:px-32 lg:mb-[60px]'></section>
        <section className='px-8 mb-[52px] md:px-12 lg:pl-[179px] lg:pr-[279px]'>
          <div className='flex flex-col gap-4 lg:gap-8'>
            <h1 className='font-sora font-normal text-[25px] text-menu-bg md:text-[35px] lg:text-[56px] lg:leading-[64px]'>
              5 Benefits of Adding a Custom Outdoor Fireplace to Your Backyard
            </h1>
            <p className='font-sora font-light text-sm leading-24 text-[#807B84] md:text-base'>
              By John Doe | Feb 14, 2023
            </p>
          </div>
        </section>
        <section className='mb-32 lg:mb-[193px]'>
          <SingleBlogContent />
        </section>
        <section className='px-8 mb-32 md:px-12 lg:px-32'>
          <ContactForm />
        </section>
        <footer className="bg-[url('/images/footer_background.png')] bg-cover bg-center">
          <Footer />
        </footer>
      </>
    </>
  )
}

export default SingleBlog
