import CardTestimony from '@/components/CardTestimony'
import ContactForm from '@/components/ContactForm'
import Footer from '@/components/Footer'
import HeroPageSection from '@/components/HeroPageSection'
import Navbar from '@/components/Navbar'
import Portfolio from '@/components/Portfolio'
import Head from 'next/head'
import { useState } from 'react'
import StyleSheet from '../styles'

function Work() {
  const [activeCategory, setActiveCategory] = useState('1')

  function handleCategory(e) {
    setActiveCategory(e.target.value)
  }
  return (
    <>
      <Head>
        <title>Our Portfolio | Schadtle Outdoor Services</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <>
        <Navbar />
        <main className='pt-[100px] mb-16'>
          <HeroPageSection
            title={`Schadtle Outdoor Services Projects`}
            content={`Our dedication to creating outdoor spaces that are carefully planned and built with outstanding workmanship and attention to detail is unwavering.`}
          />
        </main>
        <div className='px-8 md:px-12 lg:px-32 mb-12'>
          <div className='flex flex-row gap-4'>
            <p className='bg-[#F5F5F5] rounded-lg p-4 font-sora font-light text-base text-black leading-24'>
              All Category
            </p>
            <div className='flex items-center gap-[11px]'>
              <select
                onChange={handleCategory}
                className={`appearance-none bg-[url('/dropdown.svg')] bg-no-repeat bg-right pr-[44px] outline-none p-3 font-sora font-light text-base leading-24 text-black`}
                name='our-services'
                id=''
              >
                <option
                  value={'1'}
                  className='font-sora font-light text-sm  text-black outline-none'
                >
                  Select Category
                </option>
                <option
                  className='font-sora font-light text-sm text-black outline-none'
                  value={'2'}
                >
                  Retaining Walls
                </option>
                <option
                  className='font-sora font-light text-sm text-black outline-none'
                  value={'3'}
                >
                  Patio Design
                </option>
                <option
                  className='font-sora font-light text-sm text-black outline-none'
                  value={'4'}
                >
                  Yard Expansion
                </option>
              </select>
            </div>
          </div>
        </div>
        <section className='px-8 mb-32 md:px-12 lg:px-32'>
          {(activeCategory === '2' || activeCategory === '1') && (
            <div className='mb-16'>
              <Portfolio
                title={'Retaining Walls'}
                imgOne={'../images/portfolio_images/Portfolio Shot.png'}
                // imgTwo={'../images/portfolio_images/Portfolio Shot (1).png'}
                // imgThree={'../images/portfolio_images/Portfolio Shot (2).png'}
                // imgFour={'../images/portfolio_images/Portfolio Shot (3).png'}
              />
            </div>
          )}

          {(activeCategory === '3' || activeCategory === '1') && (
            <div className='mb-16'>
              <Portfolio
                title={'Patio Design'}
                // imgOne={'../images/portfolio_images/Portfolio Shot (4).png'}
                // imgTwo={'../images/portfolio_images/Portfolio Shot (5).png'}
                // imgThree={'../images/portfolio_images/Portfolio Shot (6).png'}
                // imgFour={'../images/portfolio_images/Portfolio Shot (7).png'}
              />
            </div>
          )}

          {(activeCategory === '4' || activeCategory === '1') && (
            <div className=''>
              <Portfolio
                title={'Yard Expansion'}
                // imgOne={'../images/portfolio_images/Portfolio Shot (8).png'}
                // imgTwo={'../images/portfolio_images/Portfolio Shot (9).png'}
                // imgThree={'../images/portfolio_images/Portfolio Shot (10).png'}
                // imgFour={'../images/portfolio_images/Portfolio Shot (11).png'}
              />
            </div>
          )}
        </section>
        <section className='px-8 mb-[192px] md:px-12 lg:px-32'>
          <div className='flex flex-col gap-2 mb-12'>
            <h2 className={StyleSheet.HeadingContent.heading}>Testimony</h2>
            <p className={StyleSheet.HeadingContent.content}>
              Our clients are all praise for us about our exploits
            </p>
          </div>
          <div className='grid grid-cols-1 gap-8 md:grid-cols-2 lg:grid-cols-3'>
            <CardTestimony
              desc={`Vertical pixel horizontal main group rectangle strikethrough stroke
            bold. Star community underline star font share content plugin layout
            slice. Library export font star editor library. Ellipse.`}
              img={'../images/testimonial.png'}
              name={'Tunde Ajayi'}
              location={'Location'}
              starIcon={'../star.svg'}
              alt={'tunde_ajayi'}
              source={'Trust Pilot'}
            />
            <CardTestimony
              desc={`Vertical pixel horizontal main group rectangle strikethrough stroke
            bold. Star community underline star font share content plugin layout
            slice. Library export font star editor library. Ellipse.`}
              img={'../images/testimonial.png'}
              name={'Tunde Ajayi'}
              location={'Location'}
              starIcon={'../star.svg'}
              alt={'tunde_ajayi'}
              source={'Trust Pilot'}
            />
            <CardTestimony
              desc={`Vertical pixel horizontal main group rectangle strikethrough stroke
            bold. Star community underline star font share content plugin layout
            slice. Library export font star editor library. Ellipse.`}
              img={'../images/testimonial.png'}
              name={'Tunde Ajayi'}
              location={'Location'}
              starIcon={'../star.svg'}
              alt={'tunde_ajayi'}
              source={'Trust Pilot'}
            />
          </div>
        </section>
        <section className='px-8 mb-32 md:px-12 lg:px-32'>
          <ContactForm />
        </section>
        <footer className="bg-[url('/images/footer_background.png')] bg-cover bg-center">
          <Footer />
        </footer>
      </>
    </>
  )
}

export default Work
